name: primeira pipelina
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "Primeiro step"
        run: |
          echo "Olá, esse é o primeiro step"
      - name: "Segundo step"
        run: |
          echo "Olá, esse é o segundo e último step desse job"
      - name: "Terceiro step"
        run: |
          variavel = "Teste da shell em python"
          print(variavel)
        shell: python
  segundo-job:
    name: "Segundo job"
    runs-on: ubuntu-latest
    steps:
    - name: "Verificando versão do nodejs"
      run: |
        node --version
    - name: "Istalando node mais atual"
      uses: actions/setup-node@v4.2.0
      with:
        node-version: 20.13.1
    - name: "Verificando versão do nodejs pós instalação"
      run: |
        node --version
